<script type="text/javascript">
const clientWidth = document.body.clientWidth;
const list = {
  1: {
    bjimh: require("@/assets/img/xzBj1.png"),
    icon: require("@/assets/img/xunzhaung1.png"),
    iconsamll: require("@/assets/img/arrowIcon1.png"),
    name: "Power Badge",
    name_ts: "力量徽章",
    info_en: "Buried in the depths of the ancient volcanic mountains in the Alps, with the appearance of angels, some stones began to show strange elemental reactions. When the elves passed by these rocks with turquoise light, the inside of the stones would burst into explosions. Sound. Function: It can incubate a powerful offensive angel.",
    info_ts: "埋藏在阿爾卑斯山古老火山山脈的深處，隨著天使的出現，一些石頭開始出現奇怪的元素反應。當精靈們從這些散發著綠松石光芒的岩石旁邊經過時，石頭內部就會爆炸開來。聲音。功能：可以孵化強大的進攻天使。",
    level: 1,
    countinfo: 330,
    count:0,
  },
  2: {
    bjimh: require("@/assets/img/xzBj2.png"),
    icon: require("@/assets/img/xunzhaung2.png"),
    iconsamll: require("@/assets/img/arrowIcon2.png"),
    name: "Magic Badge",
    name_ts: "魔法徽章",
    level: 2,
    countinfo: 220,
    info_en: "Existing between the mountain canyons of Angel Valley, Angel Valley adventurers climb across the canyon to collect these gems. Function: Able to incubate magical angels and fight with power offensive angels.",
    info_ts: "存在於天使谷的高山峽谷之間，天使谷的冒險者們爬過峽谷來收集這些寶石。功能：能夠孵化魔法天使，與力量攻擊天使戰鬥。",
    count:0,
  },
  3: {
    bjimh: require("@/assets/img/xzBj3.png"),
    icon: require("@/assets/img/xunzhaung3.png"),
    iconsamll: require("@/assets/img/arrowIcon3.png"),
    name: "Spirit Badge",
    name_ts: "精神徽章",
    level: 3,
    countinfo: 180,
    info_en: "In order to obtain these gems, adventurers from Angel Valley team up to defeat these beasts in the mountains surrounding Angel Valley. Function: It can incubate defensive combat angels, which can increase the defense value for the entire team.",
    info_ts: "為了獲得這些寶石，來自天使谷的冒險者聯手在天使谷周圍的山脈中擊敗這些野獸。作用：可以孵化防禦戰天使，可以增加整個隊伍的防禦值。",
    count:0,
  },
  4: {
    bjimh: require("@/assets/img/xzBj4.png"),
    icon: require("@/assets/img/xunzhaung4.png"),
    iconsamll: require("@/assets/img/arrowIcon4.png"),
    name: "Time badge",
    name_ts: "時間徽章",
    level: 4,
    countinfo: 130,
    info_en: "It exists in the deepest cave in the magic forest of Angel Valley, waiting for adventurers to collect it. Function: It can incubate rare functional angels, can increase the time of team battles, and control wild monsters to join the battle.",
    info_ts: "它存在於天使谷魔法森林最深處的洞穴中，等待冒險者們去收集。功能：可孵化稀有機能天使，增加團戰時間，控制野怪加入戰鬥。",
    count:0,
  },
  5: {
    bjimh: require("@/assets/img/xzBj5.png"),
    icon: require("@/assets/img/xunzhaung5.png"),
    iconsamll: require("@/assets/img/arrowIcon5.png"),
    name: "Mind Badge",
    name_ts: "心靈徽章",
    level: 5,
    countinfo: 90,
    info_en: "Existing in the qualified adventurers of Angel Valley, in order to strengthen the ecological development of Angel Valley, these adventurers have contributed their beloved gems. Function: Be able to incubate angels with rare attributes, get additional combat rewards, participate in the ranking contest for entering Angel Valley, and take priority in participating in various activities organized by Angel Valley.",
    info_ts: "存在於天使谷的合格冒險者中，為了加強天使谷的生態發展，這些冒險者貢獻了他們心愛的寶石。功能：可以孵化稀有屬性的天使，獲得額外的戰鬥獎勵，參加進入天使谷的排位賽，優先參加天使谷組織的各種活動。",
    count:0,
  },
  6: {
    bjimh: require("@/assets/img/xzBj6.png"),
    icon: require("@/assets/img/xunzhaung6.png"),
    iconsamll: require("@/assets/img/arrowIcon6.png"),
    name: "Soul Badge",
    name_ts: "靈魂徽章",
    level: 6,
    countinfo: 50,
    info_en: "Exist in the best quality members of the Angel Valley Adventurer Guild, the guild president collected these gems and contributed them. Function: It can incubate the angel with the highest attribute of Angel Valley, which is a symbol of the highest level players in Angel Valley, and can obtain the greatest reward for combat. Enjoy the highest gaming benefits in Angel Valley.",
    info_ts: "存在於天使谷冒險者公會最優質的成員中，公會會長收集這些寶石並貢獻出來。作用：可以孵化出天使谷屬性最高的天使，是天使谷最高等級玩家的象徵，戰鬥可以獲得最大的獎勵。享受天使谷最高的遊戲福利。",
    count:0,
  },
};
export default {
  clientWidth,
  list,
};
</script>
